name: Deploy React App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        working-directory: frontend
        run: npm install --legacy-peer-deps
      - name: Build
        working-directory: frontend
        run: CI=false npm run build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: frontend/build
      - uses: actions/deploy-pages@v2
